-- Generated by Matugen

require("base16-colorscheme").setup({
  base00 = "{{ colors.background.dark.hex }}",
  base01 = "{{ colors.surface_container_lowest.dark.hex }}",
  base02 = "{{ colors.surface_container_low.dark.hex }}",
  base03 = "{{ colors.outline_variant.dark.hex }}",
  base04 = "{{ colors.on_surface_variant.dark.hex }}",
  base05 = "{{ colors.on_surface.dark.hex }}",
  base06 = "{{ colors.inverse_on_surface.dark.hex }}",
  base07 = "{{ colors.surface_bright.dark.hex }}",

  base08 = "{{ colors.tertiary.dark.hex | lighten: -5 }}",
  base09 = "{{ colors.tertiary.dark.hex }}",
  base0A = "{{ colors.secondary.dark.hex }}",
  base0B = "{{ colors.primary.dark.hex }}",
  base0C = "{{ colors.tertiary_container.dark.hex }}",
  base0D = "{{ colors.primary_container.dark.hex }}",
  base0E = "{{ colors.secondary_container.dark.hex }}",
  base0F = "{{ colors.secondary.dark.hex | lighten: -10 }}",
})
