#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2023 Senan Kelly
# SPDX-FileCopyrightText: 2026 Nikita Mitasov
# SPDX-License-Identifier: GPL-3.0-or-later

tmp_dir="/tmp/stash"
rm -rf "$tmp_dir"

if [[ -n "$1" ]]; then
    stash decode <<<"$1" | wl-copy
    exit
fi

mkdir -p "$tmp_dir"

read -r -d '' prog <<EOF
/^[0-9]+\s<meta http-equiv=/ { next }
match(\$0, /^([0-9]+)\s(\[\[\s)?binary.*(jpg|jpeg|png|bmp)/, grp) {
    system("echo " grp[1] "\\\\\t | stash decode >$tmp_dir/"grp[1]"."grp[3])
    print \$0"\0icon\x1f$tmp_dir/"grp[1]"."grp[3]
    next
}
1
EOF
stash list | gawk "$prog"
