layer_rule=no_blur:1,no_animation:1,layer_name:hyprpicker
layer_rule=no_blur:1,no_animation:1,layer_name:selection
layer_rule=no_blur:1,no_animation:1,layer_name:wayfreeze
layer_rule=no_shadow:1,layer_name:swaync-control-center
layer_rule=no_shadow:1,layer_name:swaync-notification-window
layer_rule=animation_type_open:slide,layer_name:rofi
layer_rule=animation_type_close:zoom,layer_name:rofi

window_rule=is_term:1,app_id:foot
window_rule=is_fullscreen:1,no_focus:1,is_open_silent:1,is_tag_silent:1,monitor:HDMI-A-1,app_id:at.yrlf.wl_mirror

window_rule=is_floating:1,app_id:.blueman-manager-real
window_rule=width:1500,height:900,app_id:.blueman-manager-real
window_rule=is_floating:1,app_id:wev
window_rule=is_floating:1,app_id:zenity
window_rule=is_floating:1,width:1000,height:650,app_id:com.vysp3r.ProtonPlus
window_rule=is_floating:1,width:1500,height:900,app_id:org.pulseaudio.pavucontrol
window_rule=is_floating:1,app_id:^moe\.launcher.*$
window_rule=is_floating:1,title:^About .*$
window_rule=is_floating:1,width:370,height:650,title:^AmneziaVPN$
window_rule=is_floating:1,is_global:1,is_overlay:1,is_open_silent:1,is_tag_silent:1,no_focus:1,title:^Picture-in-Picture$
window_rule=is_floating:1,is_global:1,is_overlay:1,app_id:XEyes
window_rule=is_floating:1,is_global:1,is_overlay:1,focused_opacity:1,unfocused_opacity:0.7,offset_x:100,offset_y:100,monitor:eDP-1,title:^LiveSplit$
window_rule=is_floating:1,is_overlay:1,focused_opacity:1,unfocused_opacity:0.7,offset_x:-100,offset_y:100,monitor:HDMI-A-1,title:^NohBoard v.*$
window_rule=is_floating:1,is_global:1,is_overlay:1,app_id:swappy
window_rule=is_floating:1,animation_type_open:zoom,app_id:com.ayugram.desktop,title:^Media viewer$
window_rule=is_floating:1,width:450,height:630,app_id:com.ayugram.desktop,title:^Article$

# Twitter embeds
window_rule=is_floating:1,width:900,height:1200,app_id:com.ayugram.desktop,title:^(Cunny|Hitler|Fixup|Fx)(X|Twitter)$

window_rule=is_fullscreen:1,title:^Terraria:.*$
window_rule=is_fullscreen:1,ignore_minimize:1,ignore_maximize:1,is_tag_silent:1,title:^osu!$
window_rule=is_floating:1,width:370,height:800,app_id:^steam.*$,title:^Friends List$
window_rule=is_floating:1,app_id:^steam.*$,title:^(?!Steam$).*
window_rule=is_floating:1,is_overlay:1,is_global:1,no_focus:1,is_open_silent:1,is_tag_silent:1,focused_opacity:0.8,unfocused_opacity:0.8,offset_x:100,offset_y:100,app_id:steam,title:^notificationtoasts_.*$
window_rule=is_floating:1,width:825,height:690,app_id:waypaper
window_rule=is_floating:1,width:390,height:700,title:^Mini App:.*
window_rule=is_floating:1,app_id:qBittorrent
window_rule=is_floating:1,title:^MilkDrop$
window_rule=is_floating:0,title:^qBittorrent Enhanced Edition.*,app_id:qBittorrent
window_rule=is_floating:1,no_focus:1,is_open_silent:1,is_tag_silent:1,is_overlay:0,app_id:^agent-browser$

tag_rule=id:1,no_hide:1
tag_rule=id:2,no_hide:1
tag_rule=id:3,no_hide:1
tag_rule=id:4,no_hide:1
tag_rule=id:5,no_hide:1
tag_rule=id:6,no_hide:1
tag_rule=id:7,no_hide:1
tag_rule=id:8,no_hide:1
tag_rule=id:9,no_hide:1

monitor_rule=name:eDP-1,width:1920,height:1080,refresh:120,x:1960,y:1120
monitor_rule=name:HDMI-A-1,width:1920,height:1080,refresh:60,x:0,y:0
